#include <WPILib.h>
#include <AHRS.h>
#include <math.h>
#include <exception>
#include <algorithm>
#include <NIIMAQdx.h>
#include <nivision.h>
#include <CameraServer.h>
#include <stdio.h>
#include <limits.h>
#include <string.h>
#include <regex>